spring.application.name=ticketBooking
# Server Configuration
server.port=8080

# H2 Database configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (for development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN

# Thread Pool Configuration
ticket.booking.thread-pool.core-size=5
ticket.booking.thread-pool.max-size=10
ticket.booking.thread-pool.queue-capacity=100

# Logging
logging.level.com.ticketbooking=DEBUG
logging.level.org.springframework.security=DEBUG